browser=chrome
baseUrl=https://www.instagram.com/accounts/login/
username=srustilingaraju11@gmail.com
password=vinayaka05
implicitWait=10
explicitWait=20
instagram.access.token=your_access_token_here
